import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/** 与 `docusaurus.config.ts` 中 `docs.path` 一致：仓库根目录下的 `docs/` */
const docsRoot = () => path.join(__dirname, '..', 'docs');

/**
 * docs 一级目录 → 各对应一个顶栏「文档分区」标签 + 独立侧栏（见 buildSidebarsFromDocFolders / buildNavbarDocSidebarItems）。
 *
 * - **顶栏标签**：读 `docs/<dir>/_category_.yml` 或 `_category_.json` 的 `label`（**优先 .yml**）；
 *   无文件时仍会出现在顶栏，使用 {@link defaultLabelFromFolder} 推导。
 * - **侧栏**：`autogenerated`；各层分类元数据由 Docusaurus 读取同目录 `_category_.yml` / `.json`（可选，推荐 YAML 便于写注释）。
 */
/** 顶层文档目录 → 自动生成侧栏与顶栏；排除以 _ 或 . 开头的目录 */
export function listDocTopLevelFolders(): string[] {
  const root = docsRoot();
  if (!fs.existsSync(root)) return [];
  return fs
    .readdirSync(root, {withFileTypes: true})
    .filter(
      (e) => e.isDirectory() && !e.name.startsWith('_') && !e.name.startsWith('.'),
    )
    .map((e) => e.name)
    .sort((a, b) => a.localeCompare(b, 'zh-Hans'));
}

function readLabelFromYaml(content: string): string | undefined {
  const data = yaml.load(content) as unknown;
  if (!data || typeof data !== 'object' || Array.isArray(data)) return undefined;
  const label = (data as {label?: unknown}).label;
  return typeof label === 'string' ? label : undefined;
}

/** 读取顶栏用 label：优先 `_category_.yml`（可写注释），否则 `_category_.json`。 */
function readCategoryLabel(folder: string): string | undefined {
  const root = docsRoot();
  const ymlPath = path.join(root, folder, '_category_.yml');
  const jsonPath = path.join(root, folder, '_category_.json');
  if (fs.existsSync(ymlPath)) {
    try {
      const label = readLabelFromYaml(fs.readFileSync(ymlPath, 'utf8'));
      if (label !== undefined) return label;
    } catch {
      /* 解析失败则继续尝试 .json */
    }
  }
  if (fs.existsSync(jsonPath)) {
    try {
      const data = JSON.parse(fs.readFileSync(jsonPath, 'utf8')) as {
        label?: string;
      };
      return typeof data.label === 'string' ? data.label : undefined;
    } catch {
      return undefined;
    }
  }
  return undefined;
}

/** 无 `_category_.yml` / `.json` 时用于顶栏：由文件夹 slug 推导可读标题（与 Docusaurus 默认类似）。 */
function defaultLabelFromFolder(folder: string): string {
  return folder
    .split(/[-_/]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

/** 顶栏分区名称：有 `_category_.yml` / `.json` 的 `label` 则用之，否则 {@link defaultLabelFromFolder}。 */
export function getFolderNavbarLabel(folder: string): string {
  return readCategoryLabel(folder) ?? defaultLabelFromFolder(folder);
}

export function buildSidebarsFromDocFolders(): SidebarsConfig {
  const sidebars: SidebarsConfig = {};
  for (const folder of listDocTopLevelFolders()) {
    sidebars[`${folder}Sidebar`] = [{type: 'autogenerated', dirName: folder}];
  }
  return sidebars;
}

export function buildNavbarDocSidebarItems() {
  return listDocTopLevelFolders().map((folder) => ({
    type: 'docSidebar' as const,
    sidebarId: `${folder}Sidebar`,
    position: 'left' as const,
    label: getFolderNavbarLabel(folder),
  }));
}

/** docs 根目录存在 intro 时，顶栏加一个入口（与侧栏目录无关） */
export function navbarIntroItem():
  | {to: string; label: string; position: 'left'}
  | null {
  const root = docsRoot();
  if (fs.existsSync(path.join(root, 'intro.md'))) {
    return {to: '/docs/intro', label: '简介', position: 'left'};
  }
  if (fs.existsSync(path.join(root, 'intro.mdx'))) {
    return {to: '/docs/intro', label: '简介', position: 'left'};
  }
  return null;
}
