import fs from 'fs';
import path from 'path';
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const docsRoot = () => path.join(process.cwd(), 'docs');

/**
 * docs 一级目录 → 各对应一个顶栏「文档分区」标签 + 独立侧栏（见 buildSidebarsFromDocFolders / buildNavbarDocSidebarItems）。
 *
 * - **顶栏标签**：优先读 `docs/<dir>/_category_.json` 的 `label`；**没有该文件时仍会出现在顶栏**，
 *   使用 {@link defaultLabelFromFolder} 由文件夹名推导显示名。
 * - **侧栏**：`autogenerated`；各层分类的 `label` / `collapsed` 等仍由 Docusaurus 读取对应目录下的 `_category_.json`（可选）。
 */
/** 顶层文档目录 → 自动生成侧栏与顶栏；排除以 _ 或 . 开头的目录 */
export function listDocTopLevelFolders(): string[] {
  const root = docsRoot();
  if (!fs.existsSync(root)) return [];
  return fs
    .readdirSync(root, {withFileTypes: true})
    .filter(
      (e) => e.isDirectory() && !e.name.startsWith('_') && !e.name.startsWith('.'),
    )
    .map((e) => e.name)
    .sort((a, b) => a.localeCompare(b, 'zh-Hans'));
}

function readCategoryLabel(folder: string): string | undefined {
  const categoryFile = path.join(docsRoot(), folder, '_category_.json');
  if (!fs.existsSync(categoryFile)) return undefined;
  try {
    const data = JSON.parse(fs.readFileSync(categoryFile, 'utf8')) as {
      label?: string;
    };
    return typeof data.label === 'string' ? data.label : undefined;
  } catch {
    return undefined;
  }
}

/** 无 `_category_.json` 时用于顶栏：由文件夹 slug 推导可读标题（与 Docusaurus 默认类似）。 */
function defaultLabelFromFolder(folder: string): string {
  return folder
    .split(/[-_/]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

/** 顶栏分区名称：有 `_category_.json` 的 `label` 则用之，否则 {@link defaultLabelFromFolder}。 */
export function getFolderNavbarLabel(folder: string): string {
  return readCategoryLabel(folder) ?? defaultLabelFromFolder(folder);
}

export function buildSidebarsFromDocFolders(): SidebarsConfig {
  const sidebars: SidebarsConfig = {};
  for (const folder of listDocTopLevelFolders()) {
    sidebars[`${folder}Sidebar`] = [{type: 'autogenerated', dirName: folder}];
  }
  return sidebars;
}

export function buildNavbarDocSidebarItems() {
  return listDocTopLevelFolders().map((folder) => ({
    type: 'docSidebar' as const,
    sidebarId: `${folder}Sidebar`,
    position: 'left' as const,
    label: getFolderNavbarLabel(folder),
  }));
}

/** docs 根目录存在 intro 时，顶栏加一个入口（与侧栏目录无关） */
export function navbarIntroItem():
  | {to: string; label: string; position: 'left'}
  | null {
  const root = docsRoot();
  if (fs.existsSync(path.join(root, 'intro.md'))) {
    return {to: '/docs/intro', label: '简介', position: 'left'};
  }
  if (fs.existsSync(path.join(root, 'intro.mdx'))) {
    return {to: '/docs/intro', label: '简介', position: 'left'};
  }
  return null;
}
