import fs from 'fs';
import path from 'path';
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const docsRoot = () => path.join(process.cwd(), 'docs');

/** 顶层文档目录 → 自动生成侧栏与顶栏；排除以 _ 或 . 开头的目录 */
export function listDocTopLevelFolders(): string[] {
  const root = docsRoot();
  if (!fs.existsSync(root)) return [];
  return fs
    .readdirSync(root, {withFileTypes: true})
    .filter(
      (e) => e.isDirectory() && !e.name.startsWith('_') && !e.name.startsWith('.'),
    )
    .map((e) => e.name)
    .sort((a, b) => a.localeCompare(b, 'zh-Hans'));
}

function readCategoryLabel(folder: string): string | undefined {
  const categoryFile = path.join(docsRoot(), folder, '_category_.json');
  if (!fs.existsSync(categoryFile)) return undefined;
  try {
    const data = JSON.parse(fs.readFileSync(categoryFile, 'utf8')) as {
      label?: string;
    };
    return typeof data.label === 'string' ? data.label : undefined;
  } catch {
    return undefined;
  }
}

function defaultLabelFromFolder(folder: string): string {
  return folder
    .split(/[-_/]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

export function getFolderNavbarLabel(folder: string): string {
  return readCategoryLabel(folder) ?? defaultLabelFromFolder(folder);
}

export function buildSidebarsFromDocFolders(): SidebarsConfig {
  const sidebars: SidebarsConfig = {};
  for (const folder of listDocTopLevelFolders()) {
    sidebars[`${folder}Sidebar`] = [{type: 'autogenerated', dirName: folder}];
  }
  return sidebars;
}

export function buildNavbarDocSidebarItems() {
  return listDocTopLevelFolders().map((folder) => ({
    type: 'docSidebar' as const,
    sidebarId: `${folder}Sidebar`,
    position: 'left' as const,
    label: getFolderNavbarLabel(folder),
  }));
}

/** docs 根目录存在 intro 时，顶栏加一个入口（与侧栏目录无关） */
export function navbarIntroItem():
  | {to: string; label: string; position: 'left'}
  | null {
  const root = docsRoot();
  if (fs.existsSync(path.join(root, 'intro.md'))) {
    return {to: '/docs/intro', label: '简介', position: 'left'};
  }
  if (fs.existsSync(path.join(root, 'intro.mdx'))) {
    return {to: '/docs/intro', label: '简介', position: 'left'};
  }
  return null;
}
